const defaultState={projects:[],observations:[],actions:[],drafts:{}};let state=JSON.parse(localStorage.getItem("ci2-state")||"null")||defaultState;const save=()=>localStorage.setItem("ci2-state",JSON.stringify(state));const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function showView(id){qsa(".view").forEach(v=>v.classList.toggle("active",v.id===id));qsa(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));qs("#pageTitle").textContent=qs(`[data-view="${id}"] span`)?.textContent||"CI²";qs(".sidebar").classList.remove("open");}
qsa(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));qs("#menuBtn").onclick=()=>qs(".sidebar").classList.toggle("open");
const modal=qs("#projectModal");qsa("[data-open-modal],#newProjectBtn").forEach(b=>b.onclick=()=>modal.showModal());
qs("#saveProject").onclick=e=>{e.preventDefault();const name=qs("#projectName").value.trim();if(!name)return;state.projects.unshift({id:Date.now(),name,area:qs("#projectArea").value.trim(),problem:qs("#projectProblem").value.trim(),status:"Active",created:new Date().toLocaleDateString()});save();render();modal.close();qs("#projectForm").reset();showView("projects")};
function renderProjects(){const empty=`<div class="card"><span class="tag">READY</span><h3>No projects yet</h3><p>Create the first improvement project and the workspace will begin tracking it here.</p></div>`;qs("#projectCards").innerHTML=state.projects.length?state.projects.slice(0,6).map(p=>`<article class="card"><span class="tag">${p.status.toUpperCase()}</span><h3>${esc(p.name)}</h3><p>${esc(p.problem||p.area||"Project shell created.")}</p><small>${esc(p.area||"Unassigned area")} · ${p.created}</small></article>`).join(""):empty;qs("#projectTable").innerHTML=state.projects.length?`<table><thead><tr><th>Project</th><th>Area</th><th>Status</th><th>Created</th></tr></thead><tbody>${state.projects.map(p=>`<tr><td><strong>${esc(p.name)}</strong><br><span class="muted">${esc(p.problem||"")}</span></td><td>${esc(p.area||"—")}</td><td>${p.status}</td><td>${p.created}</td></tr>`).join("")}</tbody></table>`:"No projects yet."}
function renderObs(){qs("#obsRows").innerHTML=state.observations.length?state.observations.map(o=>`<tr><td>${o.date}</td><td>${esc(o.category)}</td><td>${o.duration} min</td><td>${esc(o.notes)}</td></tr>`).join(""):`<tr><td colspan="4" class="muted">No observations yet.</td></tr>`;const counts={};state.observations.forEach(o=>counts[o.category]=(counts[o.category]||0)+1);const max=Math.max(1,...Object.values(counts));qs("#pareto").innerHTML=Object.keys(counts).length?Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><strong>${v}</strong></div>`).join(""):`<p class="muted">Add observations to generate the first category Pareto.</p>`}
qs("#addObservation").onclick=()=>{const category=prompt("Observation category:");if(!category)return;const duration=prompt("Duration in minutes:","0")||"0";const notes=prompt("Short notes:","")||"";state.observations.unshift({date:new Date().toLocaleDateString(),category,duration,notes});save();render()};
qs("#addAction").onclick=()=>{const title=prompt("Action / countermeasure:");if(!title)return;const owner=prompt("Owner:","")||"Unassigned";state.actions.unshift({id:Date.now(),title,owner,done:false});save();render()};
function renderActions(){qs("#actionList").innerHTML=state.actions.length?state.actions.map(a=>`<article class="card"><span class="tag">${a.done?"COMPLETE":"OPEN"}</span><h3>${esc(a.title)}</h3><p>Owner: ${esc(a.owner)}</p><button class="secondary" onclick="toggleAction(${a.id})">${a.done?"Reopen":"Mark complete"}</button></article>`).join(""):`<article class="card"><h3>No actions yet</h3><p>Countermeasures and implementation tasks will appear here.</p></article>`}
window.toggleAction=id=>{const a=state.actions.find(x=>x.id===id);a.done=!a.done;save();render()};
qsa("[data-save]").forEach(el=>{el.value=state.drafts[el.dataset.save]||"";el.addEventListener("input",()=>{state.drafts[el.dataset.save]=el.value;save()})});
function render(){renderProjects();renderObs();renderActions();qs("#activeCount").textContent=state.projects.filter(p=>p.status==="Active").length;qs("#observationCount").textContent=state.observations.length;qs("#actionCount").textContent=state.actions.filter(a=>!a.done).length;qs("#completedCount").textContent=state.actions.filter(a=>a.done).length}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}render();
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("./service-worker.js").catch(err => console.warn("Service worker registration failed:", err));
  });
}
